name: Publish to PyPI

on:
  push:
    tags:
      - "v*" # Runs only when a tag starting with "v" is pushed (e.g., v1.0.0)

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry pytest  # Adjust based on your build system
          poetry install  # If using poetry, otherwise replace with pip install

      - name: Run Pytest
        run: pytest tests/

      - name: Extract version from pyproject.toml
        id: get_version
        run: echo "VERSION=$(poetry version -s)" >> $GITHUB_ENV

      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        if: success()
        run: poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
